language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run just:build

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    on_success: change
    on_failure: always
